pipeline:

  docker_dev:
    group: docker-deployment
    image: plugins/docker
    repo: kowalatech/kman
    secrets: [ docker_username, docker_password ]
    tags: dev
    when:
      branch: [develop]
      event: [push, tag]

  docker_dev:
    group: docker-deployment
    image: plugins/docker
    repo: kowalatech/kman
    secrets: [ docker_username, docker_password ]
    tags: latest
    when:
      branch: [master]
      event: [push, tag]
